import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import {randomUUID as id} from 'node:crypto';

test('administration requires MFA, scopes membership, protects the last admin and rejects revoked sessions', async () => {
 const db=new PGlite();
 try {
  await db.exec(`create role anon;create role authenticated;create role service_role;create role authenticator;
   create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
   create table auth.sessions(id uuid primary key,user_id uuid references auth.users,created_at timestamptz default now());
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;`);
  const dir=new URL('../migrations/',import.meta.url);
  for(const file of (await readdir(dir)).filter(f=>f.endsWith('.sql')).sort()) await db.exec(await readFile(new URL(file,dir),'utf8'));
  const admin=id(),manager=id(),crew=id(),other=id(),referee=id(),boat=id(),sid=id();
  for(const [uid,email] of [[admin,'admin'],[manager,'manager'],[crew,'crew'],[other,'other'],[referee,'referee']]) await db.query('insert into auth.users values($1,$2,now())',[uid,`${email}@test.example`]);
  await db.query('insert into public.platform_admins values($1)',[admin]);
  const login=async(uid,aal='aal1',session=id())=>{
   await db.exec('reset role');
   await db.query('insert into auth.sessions(id,user_id,created_at) values($1,$2,clock_timestamp()) on conflict do nothing',[session,uid]);
   await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
   await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({aal,session_id:session,iat:Math.floor(Date.now()/1000),user_metadata:{role:'admin'}})]);
   await db.exec('set role authenticated'); return session;
  };
  await login(manager,'aal2');
  await assert.rejects(db.query('select public.admin_users()'),/admin/);
  await assert.rejects(db.query('select public.admin_directory()'),/admin/);
  await assert.rejects(db.query('select public.admin_user($1)',[other]),/admin/);
  await assert.rejects(db.query('select public.admin_pending_invitations()'),/admin/);
  await assert.rejects(db.query("select public.admin_set_access($1,'admin',true)",[manager]),/admin/);
  await assert.rejects(db.query('insert into public.platform_admins values($1)',[manager]),/permission denied/);
  await login(admin);
  await assert.rejects(db.query('select public.admin_users()'),/MFA/);
  await assert.rejects(db.query('select public.admin_directory()'),/MFA/);
  await assert.rejects(db.query('select public.admin_user($1)',[other]),/MFA/);
  await assert.rejects(db.query('select public.list_creation_requests()'),/MFA/);
  assert.equal((await db.query('select public.can_create_series() allowed')).rows[0].allowed,false);
  await login(admin,'aal2');
  assert.equal((await db.query('select public.admin_users() users')).rows[0].users.length,5);
  assert.equal((await db.query('select public.admin_user($1) data',[other])).rows[0].data.id,other);
  assert.equal((await db.query('select public.admin_user($1) data',[id()])).rows[0].data,null);
  assert.deepEqual((await db.query('select public.admin_pending_invitations() invites')).rows[0].invites,[]);
  await assert.rejects(db.query("select public.admin_set_access($1,'admin',false)",[admin]),/last active/);
  await assert.rejects(db.query('select public.admin_set_account_status($1,true)',[admin]),/own account/);
  const doc={id:sid,name:'Managed series',year:2026,status:'draft',categories:[{id:id(),name:'Fleet'}],boats:[],events:[],races:[]};
  await db.query('select public.save_series($1,0,$2)',[doc,id()]);
  await db.query("select public.create_boat($1,'Boat','',null)",[boat]);
  const registered=(await db.query('select public.boat_directory() boats')).rows[0].boats;
  assert.equal(new Set(registered.map(b=>b.trackingColor)).size,registered.length);

  const granted=(await db.query("select public.grant_or_invite_boat_access($1,'other@test.example','crew') data",[boat])).rows[0].data;
  assert.equal(granted.status,'granted');
  const mail=(await db.query('select public.prepare_boat_invitation_email($1) data',[granted.id])).rows[0].data;
  assert.equal(mail.granted,true);assert.equal(mail.role,'crew');
  await assert.rejects(db.query('select public.prepare_boat_invitation_email($1)',[granted.id]),/Wait a minute/);
  const invited=(await db.query("select public.grant_or_invite_boat_access($1,'newcrew@test.example','manager') data",[boat])).rows[0].data;
  assert.equal(invited.status,'pending');
  assert.equal((await db.query("select public.admin_directory('newcrew') data")).rows[0].data.length,1);
  await login(other);
  await assert.rejects(db.query("select public.grant_or_invite_boat_access($1,'attacker@test.example','manager')",[boat]),/manager/);
  await assert.rejects(db.query('select public.accept_boat_invitation($1)',[invited.token]),/verified email/);
  await db.exec('reset role');
  const newcomer=id();await db.query("insert into auth.users values($1,'newcrew@test.example',null)",[newcomer]);
  await login(newcomer);
  await assert.rejects(db.query('select public.accept_boat_invitation($1)',[invited.token]),/verified email/);
  await db.exec('reset role');await db.query('update auth.users set email_confirmed_at=now() where id=$1',[newcomer]);
  await login(newcomer);await db.query('select public.accept_boat_invitation($1)',[invited.token]);
  assert.equal((await db.query('select public.can_manage_boat($1) allowed',[boat])).rows[0].allowed,true);
  await login(admin,'aal2');
  await db.query("select public.set_boat_member($1,'newcrew@test.example','remove')",[boat]);
  await db.query("select public.set_boat_member($1,'other@test.example','remove')",[boat]);
  await db.exec('reset role');await db.query('delete from public.boat_invitations where boat_id=$1',[boat]);await db.query('delete from auth.sessions where user_id=$1',[newcomer]);await db.query('delete from auth.users where id=$1',[newcomer]);
  await login(admin,'aal2');

  await db.exec('reset role');await db.query('insert into public.series_entries(series_id,boat_id,category_id) values($1,$2,$3)',[sid,boat,doc.categories[0].id]);
  await login(admin,'aal2');
  await assert.rejects(db.query("select public.grant_or_invite_boat_access($1,'other@test.example','manager',$2)",[boat,sid]),/applies to all races/);
  const skipper=(await db.query("select public.invite_boat_skipper($2,$1,'other@test.example') data",[boat,sid])).rows[0].data;
  assert.equal(skipper.status,'granted');
  await login(other);assert.equal((await db.query('select public.can_manage_boat($1) allowed',[boat])).rows[0].allowed,true);
  assert.equal((await db.query('select public.my_boats() data')).rows[0].data.some(b=>b.boatId===boat&&b.seriesId===sid),true);
  await db.query('select public.prepare_boat_invitation_email($1)',[skipper.id]);
  await login(admin,'aal2');await db.query("select public.set_boat_member($1,'other@test.example','remove')",[boat]);
  await db.exec('reset role');await db.query('delete from public.boat_series_members where boat_id=$1',[boat]);await db.query('delete from public.boat_invitations where boat_id=$1',[boat]);await db.query('delete from public.series_entries where boat_id=$1',[boat]);
  await login(admin,'aal2');
  const original=registered.find(b=>b.id===boat);
  await db.query("select public.save_boat_profile($1,'Boat','',null,550,'#abcdef',$2)",[boat,original]);
  const saved=(await db.query('select public.boat_directory() boats')).rows[0].boats.find(b=>b.id===boat);
  assert.equal(saved.weightKg,550); assert.equal(saved.trackingColor,'#abcdef');
  await assert.rejects(db.query("select public.save_boat_profile($1,'Boat','',null,600,'#abcdef',$2)",[boat,original]),/changed elsewhere/);
  await assert.rejects(db.query("select public.save_boat_profile($1,'Boat','',null,-1,'#abcdef',$2)",[boat,saved]),/check constraint/);
  await assert.rejects(db.query("select public.save_boat_profile($1,'Other','',null,100,'#abcdef',null)",[id()]),/already used/);
  await login(other);
  await assert.rejects(db.query("select public.save_boat_profile($1,'Boat','',null,600,'#abcdee',$2)",[boat,saved]),/owner or editor/);
  await login(admin,'aal2');

  await db.exec('reset role');
  for (let n=0;n<55;n++) await db.query('insert into public.boat_invitations(series_id,boat_id,email,created_by) values($1,$2,$3,$4)',[sid,boat,`pending${String(n).padStart(2,'0')}@test.example`,admin]);
  await db.query("insert into public.boat_invitations(series_id,boat_id,email,created_by) values($1,$2,'OTHER@test.example',$3)",[sid,boat,admin]);
  await login(admin,'aal2');
  const directory=async(q='',offset=0)=>(await db.query('select public.admin_directory($1,$2) data',[q,offset])).rows[0].data;
  assert.equal((await directory()).length,50);
  assert.equal((await directory('',50)).length,10);
  const pendingUser=(await directory('PENDING54'))[0];
  assert.equal(pendingUser.id,null);
  assert.equal(pendingUser.invitations.length,1);
  assert.equal('token' in pendingUser.invitations[0],false);
  const existing=await directory('other@');
  assert.equal(existing.length,1);
  assert.equal(existing[0].id,other);
  assert.equal(existing[0].invitations.length,1);
  await db.exec('reset role');
  await db.query("update public.boat_invitations set expires_at=now()-interval '1 day' where email='pending54@test.example'");
  await db.query("update public.boat_invitations set revoked_at=now() where email='pending53@test.example'");
  await db.query("update public.boat_invitations set accepted_at=now(),accepted_by=$1 where email='pending52@test.example'",[other]);
  await login(admin,'aal2');
  for (const q of ['pending54','pending53','pending52']) assert.deepEqual(await directory(q),[]);
  await db.exec('reset role');
  await db.query('delete from public.boat_invitations where series_id=$1',[sid]);
  await login(admin,'aal2');

  await db.query("select public.admin_set_membership($1,'series',$2,'manager')",[manager,sid]);
  await db.query("select public.admin_set_membership($1,'boat',$2,'manager')",[manager,boat]);
  await login(manager);
  await db.query("select public.set_series_member($1,'referee@test.example','official')",[sid]);
  await db.query("select public.set_boat_member($1,'crew@test.example','crew')",[boat]);
  await assert.rejects(db.query("select public.admin_set_access($1,'admin',true)",[manager]),/admin/);
  await assert.rejects(db.query("select public.set_series_member($1,'crew@test.example','admin')",[id()]),/admin/);
  await db.query('select public.save_series($1,1,$2)',[{...doc,name:'Manager edit'},id()]);
  await login(referee);
  await assert.rejects(db.query('select public.save_series($1,2,$2)',[{...doc,name:'Referee edit'},id()]),/manager/);
  await assert.rejects(db.query("select public.set_series_member($1,'crew@test.example','admin')",[sid]),/admin/);
  await login(crew);
  assert.equal((await db.query('select public.can_edit_boat($1) allowed',[boat])).rows[0].allowed,false);
  await assert.rejects(db.query("select public.set_boat_member($1,'other@test.example','manager')",[boat]),/owner/);
  const oldSession=await login(manager);
  await login(admin,'aal2');
  await db.query('select public.admin_revoke_sessions($1)',[manager]);
  await login(manager,'aal2',oldSession);
  await assert.rejects(db.query('select public.check_account_access()'),/Account access denied/);
  assert.equal((await db.query('select public.is_official($1) allowed',[sid])).rows[0].allowed,false);
  await assert.rejects(db.query("select public.create_boat($1,'Denied','',null)",[id()]),/Account access denied/);
  // A genuinely new session succeeds; merely refreshing iat did not.
  await login(manager);
  assert.equal((await db.query('select public.is_official($1) allowed',[sid])).rows[0].allowed,true);
  await login(admin,'aal2');
  await db.query('select public.admin_set_account_status($1,true)',[manager]);
  await login(manager);
  await assert.rejects(db.query('select public.check_account_access()'),/Account access denied/);
  assert.equal((await db.query('select * from public.series')).rows.length,0);
  await login(admin,'aal2');
  await db.query('select public.admin_set_account_status($1,false)',[manager]);
  await db.query("select public.admin_set_membership($1,'series',$2,'remove')",[manager,sid]);
  await login(manager);
  assert.equal((await db.query('select public.is_official($1) allowed',[sid])).rows[0].allowed,false);
  await login(admin,'aal2');
  const audit=(await db.query('select public.admin_audit() history')).rows[0].history;
  assert.ok(audit.some(row=>row.entity_table==='account_security' && row.actor_email==='admin@test.example'));
  assert.ok(audit.some(row=>row.entity_table==='boat_members'));
  await assert.rejects(db.query('delete from public.audit_log'),/permission denied/);
  await db.exec('reset role');
  const config=(await db.query("select rolconfig from pg_roles where rolname='authenticator'")).rows[0].rolconfig;
  assert.ok(config.includes('pgrst.db_pre_request=public.check_account_access'));
  await db.exec("select set_config('request.jwt.claim.sub','',false);set role anon");
  await assert.rejects(db.query('select public.admin_users()'),/permission denied/);
 } finally {await db.close();}
});
