import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
test('Vane reports are bounded, private, manual, idempotent and rate limited',async t=>{
 const db=new PGlite(); t.after(()=>db.close());
 await db.exec('create role anon; create role authenticated; create role service_role;');
 for(const file of ['202609240001_optional_diagnostics.sql','20261001051308_vane_diagnostics.sql','20261001071602_extended_vane_sensor_diagnostics.sql']) await db.exec(await readFile(new URL('../migrations/'+file,import.meta.url),'utf8'));
 const sample={up:100,imu:true,q:10,a:20,age:0,quality:3,north:true,offset:42,raw:null,hdg:-1,rej:0,gps:false,sat:0};
 const report={id:randomUUID(),installationId:randomUUID(),occurredAt:new Date().toISOString(),firmware:'0.0.34',appVersion:'0.0.34',samples:[sample]};
 const submit=r=>db.query('select public.submit_vane_diagnostic($1::jsonb) id',[JSON.stringify(r)]);
 await db.exec('set role anon');
 assert.equal((await submit(report)).rows[0].id,report.id);
 assert.equal((await submit(report)).rows[0].id,report.id);
 await assert.rejects(db.query('select * from public.diagnostic_reports'),/permission denied/);
 for(const r of [{...report,latitude:1},{...report,samples:[]},{...report,samples:Array(16).fill(sample)},{...report,samples:[{...sample,gps:null}]},{...report,samples:[{...sample,q:-1}]},{...report,samples:[{...sample,quality:4}]},{...report,samples:[{...sample,raw:999}]},{...report,samples:[{...sample,latitude:42}]},{...report,installationId:null},{...report,firmware:'secret'},{...report,occurredAt:'infinity'}]) await assert.rejects(submit(r));
 await assert.rejects(submit({...report,installationId:randomUUID()}),/conflict/);
 const sensor={mx:100,my:-200,mz:300,mq:1,ma:100,gx:10,gy:20,gz:30,bx:1,by:2,bz:3,gq:1,ga:20,acc:200,ce:5,ca:100};
 const extended={...report,id:randomUUID(),installationId:randomUUID(),samples:[{...sample,sensor}]};
 assert.equal((await submit(extended)).rows[0].id,extended.id);
 for(const invalid of [{...sensor,latitude:42},{...sensor,ce:8},{...sensor,mq:null},{...sensor,mx:1000001},{...sensor,ma:-2},{...sensor,gx:0.5}]) await assert.rejects(submit({...extended,id:randomUUID(),samples:[{...sample,sensor:invalid}]}));
 await submit({...extended,id:randomUUID(),samples:Array(15).fill({...sample,sensor:{...sensor,mx:null,ce:-1,ca:-1}})});
 for(let i=1;i<30;i++) await submit({...report,id:randomUUID()});
 await assert.rejects(submit({...report,id:randomUUID()}),/quota/);
 await db.exec('reset role');
 const stored=(await db.query('select payload from public.diagnostic_reports where id=$1',[report.id])).rows[0].payload;
 assert.equal(stored.consent,'manual'); assert.equal(stored.event,'vane');
});
