; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
test_dir = firmware/test

[env:esp32dev]
platform = espressif32@^6.4.0
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
build_src_filter =
    +<*> -<test_rlcd.cpp> -<main_esp32s3_rlcd.cpp> -<display/> -<native_stub.cpp>
build_flags = 
    -DCORE_DEBUG_LEVEL=1
    -Os
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=4
    -DCONFIG_BT_NIMBLE_MAX_BONDS=4
    -DCONFIG_BT_NIMBLE_ACL_BUF_COUNT=12
    -DCONFIG_BT_NIMBLE_ACL_BUF_SIZE=255
    -DCONFIG_NIMBLE_CPP_LOG_LEVEL=2
lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.2
    SparkFun BNO080 Cortex Based IMU
    mikalhart/TinyGPSPlus @ ^1.0.3
    4-20ma/ModbusMaster @ ^2.0.1
    h2zero/NimBLE-Arduino @ ^1.4.2
monitor_speed = 115200

[env:esp32s3-rlcd]
platform = espressif32@^6.4.0
board = esp32-s3-rlcd-n16r8
framework = arduino
upload_speed = 921600
upload_port = /dev/cu.usbmodem101
upload_flags = 
    --before=no_reset
    --after=no_reset

build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -Os
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=4
    -DCONFIG_BT_NIMBLE_MAX_BONDS=4
    -DCONFIG_BT_NIMBLE_ACL_BUF_COUNT=12
    -DCONFIG_BT_NIMBLE_ACL_BUF_SIZE=255
    -DCONFIG_NIMBLE_CPP_LOG_LEVEL=2
    -DLV_CONF_INCLUDE_SIMPLE
    -I${PROJECT_DIR}/firmware/include

build_src_filter =
    +<*> -<main_esp32dev.cpp> -<test_rlcd.cpp> -<native_stub.cpp>
lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.2
    SparkFun BNO080 Cortex Based IMU
    mikalhart/TinyGPSPlus @ ^1.0.3
    4-20ma/ModbusMaster @ ^2.0.1
    h2zero/NimBLE-Arduino @ ^1.4.2
    lvgl/lvgl @ ^8.4.0
monitor_speed = 115200

[env:native]
platform = native
test_framework = unity
test_build_src = false
build_src_filter =
    -<*>
    +<native_stub.cpp>
build_flags =
    -std=gnu++17
    -Ifirmware/include
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.2
